### ISSUE TITLE
CRM connection error

### ISSUE THREAD

**Issue by interfacemirror** [jlattimer/CRMDeveloperExtensions#100]
Hello,

I have a Dynamics 365 Online Organisation setup in Europe. I installed the extension on my visual studio 2017. When I try to create the connection, I get the below error in my Log file:

The authentication endpoint Username was not found on the configured Secure Token `Service!`
```

> 
>  Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Using User Specified Server 
> Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (Europe, Middle East and Africa) URI is = https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc
> Microsoft.Xrm.Tooling.Connector.CrmServiceClient Start: 256 : QueryLiveDiscoveryServer()
> Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : DiscoverOrganizations - Initializing Discovery Server Object with https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc
> Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - attempting to connect to CRM server @ https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc
> Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - created CRM server proxy configuration for https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc - duration: 00:00:01.4134647
> Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - proxy requiring authentication type : OnlineFederation 
> Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: Microsoft.Xrm.Sdk
> Method	: GetIssuerEndpoint
> Date	: 5/19/2017
> Time	: 5:32:47 PM
> Error	: The authentication endpoint Username was not found on the configured Secure Token Service!
> Stack Trace	: at Microsoft.Xrm.Sdk.Client.IssuerEndpointDictionary.GetIssuerEndpoint(TokenServiceCredentialType credentialType)
>    at Microsoft.Xrm.Sdk.Client.AuthenticationCredentials.get_IssuerEndpoint()
>    at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateInternal(AuthenticationCredentials authenticationCredentials)
>    at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateWithADFSForOrgId(AuthenticationCredentials authenticationCredentials, Uri identifier)
>    at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.AuthenticateOnlineFederationInternal(AuthenticationCredentials authenticationCredentials)
>    at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1.Authenticate(AuthenticationCredentials authenticationCredentials)
>    at Microsoft.Xrm.Sdk.Client.DiscoveryServiceConfiguration.Authenticate(AuthenticationCredentials authenticationCredentials)
>    at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.ClaimsIFDFailOverAuth[T](IServiceManagement`1 servicecfg, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, Int32 depthLevel, Boolean tryNetworkCred)
>    at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
>    at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
>    at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer)
>    at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
>    at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
> ======================================================================================================================
> 
> Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
> Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : Failed to Execute Command - WhoAmI
> Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: Microsoft.Xrm.Tooling.Connector
> Method	: CrmCommand_Execute
> Date	: 5/19/2017
> Time	: 5:32:47 PM
> Error	: Object reference not set to an instance of an object.
> Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CrmCommand_Execute(OrganizationRequest req, String errorStringCheck)

```

**Comment by mailsrikanta** [comment]
Hi, 
I have installed the "Dynamics CRM & 365 Developer Extensions" witn VS 2015 with MSCRM 2016 onPremisis

When I am trying to connect CRM getting errors.

![image](https://cloud.githubusercontent.com/assets/1763074/26505435/70ab9e14-4251-11e7-9f2c-18d7dc6dad3a.png)

And getting the below Error:
![image](https://cloud.githubusercontent.com/assets/1763074/26505479/9fc24b80-4251-11e7-95ff-f38f42595570.png)

Can you please let me know the root cause for the same to fix it.

**Comment by jlattimer** [comment]
Looks to be the same error that pops up for some people - not exactly sure why still. Seems to be fairly random.

**Comment by interfacemirror** [comment]
Well, the issue is about the network and the way CRM server is accessed. In my case, the client is federated its ActiveDirectory in Azure and I am also able to login using Live ID. The network topology is in such a way that for accessing the organization using SDK, I will need to be connected to VPN. However, with Live ID the story is different because even connecting to VPN does not allow me to connect using Live ID. 

I am wondering if there is any fix or idea on how to connect to a federated organization using Live ID?

**Comment by jlattimer** [comment]
Not sure what to tell you there. If you can't connect via any of the standard CRM connection options there isn't really much I can do to help.
