### ISSUE TITLE
Unable to connect to Dynamics 365

### ISSUE THREAD

**Issue by vdx660** [jlattimer/CRMDeveloperExtensions#79]
This error appears when trying to connect to a Dynamics 365 Instance

Error Connecting To CRM: Metadata contains a reference that cannot be resolved: 'https://xxx.crm5.dynamics.com/XRMServices/2011/Organization.svc?wsdl=wsdl0'.
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever retriever)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(Uri address, MetadataExchangeClientMode mode)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.OrganizationServiceConfiguration..ctor(Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateConfiguration[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Client.Services.OrganizationService.CreateServiceConfiguration(CrmConnection connection)
   at Microsoft.Xrm.Client.Services.OrganizationService.GetServiceConfiguration(CrmConnection connection)
   at Microsoft.Xrm.Client.Services.OrganizationService.ToOrganizationServiceProxy(CrmConnection connection)
   at Microsoft.Xrm.Client.Services.OrganizationService.ToOrganizationService(CrmConnection connection)
   at Microsoft.Xrm.Client.Services.OrganizationService.<>c__DisplayClass2.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.Xrm.Client.Services.OrganizationService.InnerOrganizationService.get_Value()
   at Microsoft.Xrm.Client.Services.OrganizationService.Dispose()
   at CrmConnectionWindow.Connection.ConnectToCrm(String connectionString)

**Comment by jlattimer** [comment]
Will be fixed in the next release - hopefully within the next week.

**Comment by arnongold** [comment]
Hi, Any news on this ?

**Comment by jlattimer** [comment]
Still in process I'm afraid, found a scenario where authentication doesn't work that I still need to work through

**Comment by PJ-GitHub-DC** [comment]
Hi, Any updates on this?

**Comment by jlattimer** [comment]
Almost done

**Comment by jlattimer** [comment]
New version released which will connect to 8.2 orgs
