### ISSUE TITLE
Error connecting to CRM after update to 1.3.4

### ISSUE THREAD

**Issue by pneidhoefer** [jlattimer/CRMDeveloperExtensions#85]
Hi!

After updating to v.1.3.4. the connection to an On-Premise CRM isn't possible any more.

Error Connecting To CRM: Object reference not set to an instance of an object.
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.Execute(OrganizationRequest request)
   at CrmConnectionWindow.Connection.ConnectToCrm(String connectionString)

Please fix this. 

Best Regards,

Philipp

**Comment by jlattimer** [comment]
Enable Xrm.Tooling logging in the Options area, try connecting again, and post the log.

**Comment by pneidhoefer** [comment]
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Discovery URI is = http://192.168.188.47:5555/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : DiscoverOrganizations - Initializing Discovery Server Object with http://192.168.188.47:5555/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - attempting to connect to CRM server @ http://192.168.188.47:5555/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - created CRM server proxy configuration for http://192.168.188.47:5555/XRMServices/2011/Discovery.svc - duration: 00:00:00.0180247
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - proxy requiring authentication type : ActiveDirectory 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - service proxy created - total create duration: 00:00:00.0180247
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : ERROR REQUESTING ORGS FROM THE DISCOVERY SERVER
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: mscorlib
Method	: HandleReturnMessage
Date	: 14.12.2016
Time	: 08:39:29
Error	: SOAP security negotiation with 'http://192.168.188.47:5555/XRMServices/2011/Discovery.svc' for target 'http://192.168.188.47:5555/XRMServices/2011/Discovery.svc' failed. See inner exception for more details.
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Security.IssuanceTokenProviderBase`1.DoNegotiation(TimeSpan timeout)
   at System.ServiceModel.Security.SspiNegotiationTokenProvider.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Security.WrapperSecurityCommunicationObject.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.CommunicationObjectSecurityTokenProvider.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SymmetricSecurityProtocol.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Security.WrapperSecurityCommunicationObject.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.ClientSecurityChannel`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceProxy.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
======================================================================================================================
Inner Exception Level 1	: 
Source	: System.ServiceModel
Method	: GetOutgoingBlob
Date	: 14.12.2016
Time	: 08:39:29
Error	: The Security Support Provider Interface (SSPI) negotiation failed.
Stack Trace	: at System.ServiceModel.Security.WindowsSspiNegotiation.GetOutgoingBlob(Byte[] incomingBlob, ChannelBinding channelbinding, ExtendedProtectionPolicy protectionPolicy)
   at System.ServiceModel.Security.SspiNegotiationTokenProvider.GetNextOutgoingMessageBody(Message incomingMessage, SspiNegotiationTokenProviderState sspiState)
   at System.ServiceModel.Security.IssuanceTokenProviderBase`1.GetNextOutgoingMessage(Message incomingMessage, T negotiationState)
   at System.ServiceModel.Security.IssuanceTokenProviderBase`1.DoNegotiation(TimeSpan timeout)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: mscorlib
Method	: HandleReturnMessage
Date	: 14.12.2016
Time	: 08:39:29
Error	: SOAP security negotiation with 'http://192.168.188.47:5555/XRMServices/2011/Discovery.svc' for target 'http://192.168.188.47:5555/XRMServices/2011/Discovery.svc' failed. See inner exception for more details.
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Security.IssuanceTokenProviderBase`1.DoNegotiation(TimeSpan timeout)
   at System.ServiceModel.Security.SspiNegotiationTokenProvider.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Security.WrapperSecurityCommunicationObject.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Security.CommunicationObjectSecurityTokenProvider.Open(TimeSpan timeout)
   at System.ServiceModel.Security.SymmetricSecurityProtocol.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Security.WrapperSecurityCommunicationObject.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.SecurityChannelFactory`1.ClientSecurityChannel`1.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.Discovery.IDiscoveryService.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Sdk.Client.DiscoveryServiceProxy.Execute(DiscoveryRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, NetworkCredential networkCredential)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: System.ServiceModel
Method	: GetOutgoingBlob
Date	: 14.12.2016
Time	: 08:39:29
Error	: The Security Support Provider Interface (SSPI) negotiation failed.
Stack Trace	: at System.ServiceModel.Security.WindowsSspiNegotiation.GetOutgoingBlob(Byte[] incomingBlob, ChannelBinding channelbinding, ExtendedProtectionPolicy protectionPolicy)
   at System.ServiceModel.Security.SspiNegotiationTokenProvider.GetNextOutgoingMessageBody(Message incomingMessage, SspiNegotiationTokenProviderState sspiState)
   at System.ServiceModel.Security.IssuanceTokenProviderBase`1.GetNextOutgoingMessage(Message incomingMessage, T negotiationState)
   at System.ServiceModel.Security.IssuanceTokenProviderBase`1.DoNegotiation(TimeSpan timeout)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : Failed to Execute Command - WhoAmI
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: Microsoft.Xrm.Tooling.Connector
Method	: CrmCommand_Execute
Date	: 14.12.2016
Time	: 08:39:29
Error	: Object reference not set to an instance of an object.
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CrmCommand_Execute(OrganizationRequest req, String errorStringCheck)
======================================================================================================================


I found a solution for now, but I have to create a base 64 connection string manually, and paste it to the CRMDeveloperExtensions.config. Then everything works fine.

**Comment by jlattimer** [comment]
Out of curiosity, what did you need to change to make it work?

**Comment by bobbyangers** [comment]
Can we get the previous version that worked ?

**Comment by jlattimer** [comment]
The previous version is posted in the releases area

**Comment by jlattimer** [comment]
Also curious if this post applies - being cross domain...
http://sandrinodimattia.net/early-binding-tips-and-tricks-for-dynamics-crm-2011/

**Comment by bobbyangers** [comment]
In the file >>  CrmConnectionWindow / Connection.xaml.cs 
There seem to be missing some code for the switch case for "On-premises with provided user credentials" when trying to build the connectionstring

`161         private string CreateConnectionString(ComboBoxItem item) 
162         { 
163             var sb = new StringBuilder(); 
164 
 
165             sb.AppendFormat("Url={0};", Url.Text.Trim()); 
166 
 
167             switch (item.Content.ToString()) 
168             { 
169                 case "Online using Office 365": 
170                     sb.AppendFormat("Username={0};Password='{1}';", Username.Text.Trim(), Password.Password.Trim().Replace("'", "''")); 
171                     sb.Append("AuthType=Office365;"); 
172                     break; 
173                 case "On-premises (IFD) with claims": 
174                     sb.AppendFormat("Domain={0};", Domain.Text.Trim()); 
175                     sb.AppendFormat("Username={0};Password='{1}';", Username.Text.Trim(), Password.Password.Trim().Replace("'", "''")); 
176                     sb.Append("AuthType=IFD;"); 
177                     break; 
178                 case "On-premises with provided user credentials": 
179                 case "On-premises using Windows integrated security": 
180                     sb.Append("AuthType=AD;"); 
181                     break; 
182                 case "OAuth": 
183                     sb.AppendFormat("Username={0};Password='{1}';", Username.Text.Trim(), Password.Password.Trim().Replace("'", "''")); 
184                     sb.AppendFormat("AppId={0};", AppId.Text.Trim()); 
185                     sb.Append("LoginPrompt=Never;"); 
186                     sb.Append("AuthType=OAuth;"); 
187                     break; 
188             } 
189 
 
190             sb.Append("RequireNewInstance=true;"); 
191             return sb.ToString(); 
192         } 
`

**Comment by bobbyangers** [comment]
Please provide the link to the release area, it is neither in the menu nor is it on the gallerie site.

**Comment by jlattimer** [comment]
https://github.com/jlattimer/CRMDeveloperExtensions/releases

**Comment by bobbyangers** [comment]
Thanks for the link, may useful to be in Readme.md

As for my previous comment, it seems the Connection is built one way for "display" and is correct.  But the function CreateConnectionString() is missing some code in the switch statement. 

Do you want me to clone the repo and submit my suggested changes ?

--Robert

**Comment by jlattimer** [comment]
Go for it

**Comment by bobbyangers** [comment]
Hi,
Having the wrong version of VS and missing tools apparently....
Anyway,

I believe that if you change the method in the following file:
**CrmConnectionWindow / Connection.xaml.cs**
` private string CreateConnectionString()
 {

    return ConnString.Text;
}`

instead of recaculcating the connections, reuse the one generated on the screen, it'll work fine.

**Comment by jonchen0205** [comment]
Hi,

was there any resolution to this? I'm experiencing the same issue, and cannot locate the cs file bobbyangers mentioned above.

**Comment by jlattimer** [comment]
I put up a version with the suggestion suggested by @bobbyangers and tested it on an on premise 2016 server w/o IFD and was able to connect. If someone else could please verify that would be great. 

Once checked, please uninstall and reinstall a previous version until the official release comes down from the VS Marketplace.
https://github.com/jlattimer/CRMDeveloperExtensions/releases/tag/v1.3.4.1

**Comment by gashupl** [comment]
I've checked 1.3.4.1 version and I'm still getting the same error ("object reference is not set..."). I've tried to connect to Dynamics 365 (both online and on-premise) and CRM 2016 on-premise.

**Comment by jlattimer** [comment]
@gashupl - the fix was only for on premise using credentials - if you have a problem connecting, open a new issue and post the log as described above

**Comment by VexinSoft** [comment]
Hello

I got the laste version 1.3.4.0 and cannot connect to CRM 365, with webresource porject when trying to create a connection string the window still open and nothing append.

Thanks in advance.

Gilles

**Comment by meikelenboom** [comment]
I've checked with 1.3.4.1 and it solved the issue for me. I haven't checked with any other environments other than onpremises with user provided credentials.

**Comment by VexinSoft** [comment]
It doesn't solved the problem with crm 365 online. Cannot create connection string

**Comment by cbritton123** [comment]
1.3.4.1 pre-release solved the on-premise connection issue for me as well.

**Comment by jlattimer** [comment]
Published official 1.3.4.1 release for the on premise issue - recommend if anyone had the pre-release to unintall and get the latest from the gallery. Any new items should be raised on a new issue
