### ISSUE TITLE
Solution Packager - Unable to connect to CRM

### ISSUE THREAD

**Issue by Panoone** [jlattimer/CRMDeveloperExtensions#91]
I am continuing to receive the following error when attempting to add a connection to the Solution Packager for our Dynamics CRM 2016 Professional online domain.

`Error Connecting To CRM: Object reference not set to an instance of an object.
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.Execute(OrganizationRequest request)
   at CrmConnectionWindow.Connection.ConnectToCrm(String connectionString)`

The host URL is in the format: https://mydomain.crm6.dynamics.com

- I have pre-installed the Dynamics 365 SDK and UII for CRM (should these be installed to a specific path?).
- I then installed your CRM Developer Extensions and configured the path to the SDK Bin directory for the Solution Packager.

Are there any other configurations or references I need to make anywhere?

**Comment by synesthesia** [comment]
I've been seeing that a bit lately, but it is happening at the same time as we have seen other connection issues with CRM Onlie (in our case crm4 - EMEA). There is a curernt Microsoft

**Comment by jlattimer** [comment]
Can you enable the Xrm.Tooling logging in VS under Tools -> Options -> Dev Extensions and then post the log. Pretty sure I know what the log output is going to be but I'd like to see it to be sure. I ran into an issue during development this last iteration where I could not access a new 8.2 org from 2 of my machines but only from VS 2012 - yet on both machines I it worked fine from VS 2013 & VS 2015. Then on a VM I had with VS 2012 only, it worked as expected either. 

So if you could post the logs, that would be great. Hopefully that will give me some more details to go back to my Microsoft contacts with to troubleshoot further.

**Comment by Panoone** [comment]
I enabled logging and tried connecting again. This time it was successful, so it appears to be a sporadic problem on the Dynamics' side.

**Comment by synesthesia** [comment]
I'm seeing this now on a new project. Error log is 
```
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Using User Specified Server 
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : Trying Live Discovery Server, (Europe, Middle East and Africa) URI is = https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Start: 256 : QueryLiveDiscoveryServer()
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Information: 8 : DiscoverOrganizations - Initializing Discovery Server Object with https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : DiscoverOrganizations - attempting to connect to CRM server @ https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: System.ServiceModel
Method	: Retrieve
Date	: 15/02/2017
Time	: 10:50:51
Error	: Metadata contains a reference that cannot be resolved: 'https://disco.crm4.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=8.2'.
Stack Trace	: at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.ResolveNext(ResolveCallState resolveCallState)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(MetadataRetriever retriever)
   at System.ServiceModel.Description.MetadataExchangeClient.GetMetadata(Uri address, MetadataExchangeClientMode mode)
   at Microsoft.Xrm.Sdk.Client.ServiceMetadataUtility.RetrieveServiceEndpointMetadata(Type contractType, Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfiguration`1..ctor(Uri serviceUri, Boolean checkForSecondary)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri, Boolean enableProxyTypes, Assembly assembly)
   at Microsoft.Xrm.Sdk.Client.ServiceConfigurationFactory.CreateManagement[TService](Uri serviceUri)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.CreateAndAuthenticateProxy[T](IServiceManagement`1 servicecfg, Uri ServiceUri, Uri homeRealm, ClientCredentials userCredentials, ClientCredentials deviceCredentials, String LogString)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.DiscoverOrganizations(Uri discoveryServiceUri, Uri homeRealmUri, ClientCredentials clientCredentials, ClientCredentials deviceCredentials)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.QueryLiveDiscoveryServer(Uri discoServer)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.FindCrmOnlineDiscoveryServer(CrmOnlineDiscoveryServers onlineServerList, Boolean useO365Servers)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================
Inner Exception Level 1	: 
Source	: System
Method	: GetResponse
Date	: 15/02/2017
Time	: 10:50:51
Error	: Unable to connect to the remote server
Stack Trace	: at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper)
======================================================================================================================
Inner Exception Level 2	: 
Source	: System
Method	: DoConnect
Date	: 15/02/2017
Time	: 10:50:51
Error	: No connection could be made because the target machine actively refused it 127.0.0.1:8888
Stack Trace	: at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Verbose: 16 : Failed to Execute Command - WhoAmI
Microsoft.Xrm.Tooling.Connector.CrmServiceClient Error: 2 : Source	: Microsoft.Xrm.Tooling.Connector
Method	: CrmCommand_Execute
Date	: 15/02/2017
Time	: 10:50:51
Error	: Object reference not set to an instance of an object.
Stack Trace	: at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CrmCommand_Execute(OrganizationRequest req, String errorStringCheck)
======================================================================================================================


```

**Comment by bwmodular** [comment]
Do you possibly have the Microsoft software development toolkit beta installed as well. A recent update to this has caused many issues with connectivity - see this thread for more details and a potential fix. This may be unrelated, but thought it worth mentioning.

**Comment by synesthesia** [comment]
Don't think so @bwmodular but I'll check.

Looking in our Office365portal I see a recent set of incidents that Microsoft have described like this:

> CR93320 - Components/Features - Service restored
> Service restored - 11 Feb 2017 20:57
> 
> Title: Organizational sign-in issues using XRM tooling connectors and SDK tools
> 
> User Impact: Users experienced issues signing in to their organizations when using XRM tooling connectors and SDK tools
> 
> Final Status: Engineers reset the web servers, then verified functionality of the XRM tooling connectors and SDK tools.
> 
> 
> User Experience: Affected users experienced unhandled exception errors and sign-in failures when using XRM tooling connectors and SDK tools to access their organizations. Users were able to access their organizations via the standard user interface.
> 
> 
> Customer Impact: A subset of customers hosted in the North America, South America, India, Japan, Asia Pacific, Oceania, and the Europe, Middle East and Africa regions, as well as a subset of customers in the government cloud environment.
> 
> 
> Incident Start Time: Friday, February 10, 2017, 12:43 PM UTC
> 
> 
> Incident End Time: Saturday, February 11, 2017, 2:57 PM UTC
> 
> 
> Next Steps: A Post-Incident Report will be available within 5 business days.
>
