### ISSUE TITLE
Web Resource Deployer - Connects and crashes Visual Studio

### ISSUE THREAD

**Issue by ashwinravi** [jlattimer/CRMDeveloperExtensions#93]
I have the latest version of the Developer Extensions installed - 1.3.4.1 and am using Visual Studio 2015.

Here are the steps to reproduce the issue:

1. Right click on my Web resources project to select CRM Developer Extensions -> Web Resource Deployer.

2. On the Web resource deployer window, click on the Add Connection button to create a new connection as shown below:
     
![image](https://cloud.githubusercontent.com/assets/2646050/22759630/fc2ceb9e-ee07-11e6-86aa-574d212dff9e.png)

3. Click Connect. It displays the 'Connecting' message and is also able to connect successfully as shown in the Output window below. As soon as that happens, it crashes Visual Studio and ends up restarting. See the screenshots below:

![image](https://cloud.githubusercontent.com/assets/2646050/22759771/8b52c078-ee08-11e6-8d27-5174dd003ea5.png)
![image](https://cloud.githubusercontent.com/assets/2646050/22759789/9700aade-ee08-11e6-9977-7f8cb1d01f10.png)
![image](https://cloud.githubusercontent.com/assets/2646050/22759796/9d4f4c56-ee08-11e6-8070-df3df3e401bb.png)
![image](https://cloud.githubusercontent.com/assets/2646050/22759799/a230d9c4-ee08-11e6-8019-c383d34fd17c.png)

I am also attaching the Dev Extensions log file below it it helps but it doesn't have any indication of errors.
[CRMDevExXrmToolingLog282017.log.txt](https://github.com/jlattimer/CRMDeveloperExtensions/files/762090/CRMDevExXrmToolingLog282017.log.txt)

**Comment by ashwinravi** [comment]
@jlattimer Hi Jason just created a new bug that is preventing us from using this tool on our project. I would greatly appreciate it if you can help troubleshoot and get to the bottom of it. Maybe you've seen this on your projects or heard from other about it.

**Comment by jlattimer** [comment]
This one is new to me - it's connecting to CRM as it should. Is this multiple people or just one?

**Comment by fizz80** [comment]
VS 2015 crashes for me as well.

**Comment by jlattimer** [comment]
Have you tried un-installing & re-installing the extension? Are you using any other extensions that might be conflicting? Might help to disable some and see if it resolves - might point to an underlying reason for the crash. I'm inclined to think it's something specific the the environment as crashes in VS 2015 seem to be limited to these few instances.

**Comment by mizzou626** [comment]
I'm running into the same issue even after uninstalling and reinstalling the extension. Also, I noticed that I can't see any projects from the list which seems to be associated to this error. Has anyone else noticed this?

**Comment by ashwinravi** [comment]
I was able to get this fixed on my machine. Here are all the things I tried and one of the last 2 options may have helped resolve the problem:
- Uninstalling and reinstalling the extension multiple times - DID NOT RESOLVE THE ISSUE FOR ME.
- Restarted my machine multiple times - DID NOT RESOLVE THE ISSUE FOR ME.
- Installed all latest versions of the Visual Studio product updates by going to Tools->Extensions and Updates - THIS MAY HAVE HELPED.
- The CRMDeveloperExtensions.config file from the previous version is part of Source control. We have had to check out the file locally in order for the tool to be able to make updates to it. Something may have gone wrong there, so I undid the changes and checked it out again from VSTS. - THIS MAY HAVE HELPED AS WELL.

**Comment by EJPronk** [comment]
I have the same problem. I tried all above, but keep getting the issue. Included are erorrs from my event log. Hopefully you can resolve it.
[VS CRMDeveloperExtension Crash.zip](https://github.com/jlattimer/CRMDeveloperExtensions/files/824722/VS.CRMDeveloperExtension.Crash.zip)

**Comment by gashupl** [comment]
Having the same problem. Reinstalling and updating VS/VS Extensions does not solve it. 
Info from event viewer:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at CommonResources.SharedConfigFile.ConfigFileExists(EnvDTE.Project)
   at CommonResources.ConnectionPane.AddConnection_Click(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.ReRaiseEventAs(System.Windows.DependencyObject, System.Windows.RoutedEventArgs, System.Windows.RoutedEvent)
   at System.Windows.UIElement.OnMouseUpThunk(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by Juanlor** [comment]
Hi,

I checked that this issue was caused due to the use of project folders. In my case the issue appeared when I moved my web project from solution root to a project folder. After this change and re-opening the solution, the first drop down list (Project) was empty and I couldn't create any connection to CRM and Visual Studio was closed:

[Project drop down list empty](https://cloud.githubusercontent.com/assets/1775369/24971222/76d32a6c-1fb7-11e7-95ce-2c5e0645a6ff.png)

[eventlog.txt](https://github.com/jlattimer/CRMDeveloperExtensions/files/917399/eventlog.txt)

I hope this information can be useful to solve this issue.
Best regards.

**Comment by gashupl** [comment]
In my case – bug was also related with folders. Unfortunately, because of complication level of our VS solutions – it makes CRM Developer Extensions useless for us :( because I cannot imagine building coded solutions without using folders containing VS projects.

**Comment by maerger** [comment]
@Juanlor : Support for project folders is a known issue - we have same problem here. And already mentioned several times. It may not been linked to this one...
