### ISSUE TITLE
Error Updating Assembly In CRM: Input string was not in a correct format.

### ISSUE THREAD

**Issue by augustgugi** [jlattimer/CRMDeveloperExtensions#95]
When I am trying to deploy custom Plugin using Plugin Deployer ti fails with the message(Error Updating Assembly In CRM: Input string was not in a correct format.).

I am using the latest version of CRM Developer Extensions(1.3.4.1) and Visual Studio 2015.

Here is the stack trace:

Error Updating Assembly In CRM: Input string was not in a correct format.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at PluginDeployer.PluginList.UpdateCrmAssembly(AssemblyItem assemblyItem, CrmServiceClient client)

**Comment by MadButcher** [comment]
I had the same issue. 
The plugin was using the default Build and Revision Numbers (1.0.*) the AssemblyInfo.cs.
Version.Parse doesn't like that format. 
Just change the Version string in AssemblyInfo to a number without wildcards (eg.: "1.1.0.0").
